### ISSUE TITLE
tf 2.13 tf 2.14 -  loading model backward compatibility 

### ISSUE THREAD

**Issue by Chizkiyahu** [sony/mct_quantizers#67]
mct_quantizers have a backward compatibility bug  
when the model is created with mct_quantizers tf 2.13 and loading with tf 2.14
also, the test did not check  backward compatibility https://github.com/sony/mct_quantizers/pull/66

model for example - created with tf 2.13.1
[tf_conv2d_model_0.keras.zip](https://github.com/sony/mct_quantizers/files/12845402/tf_conv2d_model_0.keras.zip)

error log 
```
sdspTraceback (most recent call last):
  File "/path/to/codetensorflow/tf_parser/tf_reader.py", line 53, in _load_model
    model = keras_load_quantized_model(model_path, compile=False)
  File "/path/to/env/def/lib/python3.9/site-packages/mct_quantizers/keras/load_model.py", line 62, in keras_load_quantized_model
    return tf.keras.models.load_model(filepath, custom_objects=qi_custom_objects, compile=compile, **kwargs)
  File "/path/to/env/def/lib/python3.9/site-packages/keras/src/saving/saving_api.py", line 254, in load_model
    return saving_lib.load_model(
  File "/path/to/env/def/lib/python3.9/site-packages/keras/src/saving/saving_lib.py", line 281, in load_model
    raise e
  File "/path/to/env/def/lib/python3.9/site-packages/keras/src/saving/saving_lib.py", line 269, in load_model
    _load_state(
  File "/path/to/env/def/lib/python3.9/site-packages/keras/src/saving/saving_lib.py", line 466, in _load_state
    _load_container_state(
  File "/path/to/env/def/lib/python3.9/site-packages/keras/src/saving/saving_lib.py", line 534, in _load_container_state
    _load_state(
  File "/path/to/env/def/lib/python3.9/site-packages/keras/src/saving/saving_lib.py", line 435, in _load_state
    trackable.load_own_variables(weights_store.get(inner_path))
  File "/path/to/env/def/lib/python3.9/site-packages/keras/src/engine/base_layer.py", line 3531, in load_own_variables
    raise ValueError(
ValueError: Layer 'keras_activation_quantization_holder_1' expected 1 variables, but received 0 variables during loading. Expected: ['optimizer_step:0']

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/codecommon/main.py", line 161, in execute
    g = self.convert_model(args.input_path, vis_dir)
  File "/path/to/codecommon/main.py", line 60, in convert_model
    parser = self.get_parser(model_path, vis_dir)
  File "/path/to/codecommon/main.py", line 56, in get_parser
    return self._parser_cls(model_path, vis_dir)
  File "/path/to/codetensorflow/tf_parser/tf_parser.py", line 41, in __init__
    super().__init__(model_path, TensorflowReader, vis_path)
  File "/path/to/codecommon/parsers/base_parser.py", line 46, in __init__
    self.reader = reader(fw_model)
  File "/path/to/codecommon/parsers/base_reader.py", line 51, in __init__
    self.model = self._load_model(fw_model)
  File "/path/to/codetensorflow/tf_parser/tf_reader.py", line 58, in _load_model
    raise RuntimeError(msg) from e
RuntimeError: Failed to load the model.
2023-10-09 14:24:49,817 - ERROR - CODE: [EXEC] Failed to load the model. [/path/to/codecommon/logger.py:154]
```

**Comment by ofirgo** [comment]
This is a compatibility issue with TF 2.14 that is not related to MCTQ.
An [issue](https://github.com/tensorflow/tensorflow/issues/62363) was reported in TF repo.

**Comment by dunght004** [comment]
You should pip install pre version. I was resolved this error by installed the pre version.
